---
# <https://docs.ansible.com/ansible/latest/modules/dconf_module.html>
- name: Install psutil Python library (required by dconf Ansible module)
  ansible.builtin.dnf:
    state: present
    name: "python{{ ansible_python['version']['major'] }}-psutil"

- name: Install dconf-editor
  ansible.builtin.dnf:
    state: present
    name: dconf-editor
