---
- name: Add the flathub Flatpak repository remote to the user installation
  vars: { ansible_become: false }
  community.general.flatpak_remote:
    method: user
    state: present
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatseal to manage Flatpak permissions
  vars: { ansible_become: false }
  community.general.flatpak:
    method: user
    state: present
    name: com.github.tchx84.Flatseal
