---
- name: Include tasks defined in this role
  ansible.builtin.include_tasks: "{{ tasks }}"
  loop:
    - configure-flatpak.yml
    - configure-dconf.yml
    - configure-display.yml  # TODO: Map dependency on configure-dconf.yml
    - install-codecs.yml
  loop_control:
    loop_var: tasks
