---
- name: Run individual role specified by -e role=<role>
  hosts: workstations
  tasks:
  - name: Include {{ role }} role
    include_role:
      name: "{{ role }}"
...
# References:
# - <https://stackoverflow.com/questions/36484980/use-ansible-facts-in-an-ansible-ad-hoc-command>
# - <https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-roles>
# - <https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#dynamic-vs-static>
