---
- name: Install build tools
  dnf:
    state: present
    name:
      - automake
#     - cargo
      - clang
      - cmake
      - g++
      - libtool
      - pkgconf-pkg-config

- name: Install diff and merge tools
  dnf:
    state: present
    name:
      - meld
      # TODO: Add more tools
  tags:
    - graphical

# Note that there is some overlap here with editing.yml
- name: Install search tools
  dnf:
    state: present
    name:
      - fd-find
      - fzf
      - ripgrep
      - the_silver_searcher

# Bloat? Did somebody say "bloat"?!
- name: Install shells
  dnf:
    state: present
    name:
      - dash
      - fish
      - ksh
      - tcsh
      - zsh

- name: Install preferred terminal multiplexer
  dnf:
    state: present
    name:
      - tmux

- name: Install preferred terminal emulator
  dnf:
    state: present
    name:
      - xterm
      # TODO: Investigate other options (e.g. urxvt, st)
  tags:
    - graphical
