---
- name: Install build tools
  dnf:
    state: present
    name:
      - automake
      - cargo
      - clang
      - cmake
      - g++
      - libtool
      - pkgconf-pkg-config

- name: Install diff and merge tools
  dnf:
    state: present
    name:
      - meld
      # TODO: Add more tools

# Note that there is some overlap here with editing.yml
- name: Install search tools
  dnf:
    state: present
    name:
      - fd-find
      - fzf
      - ripgrep
      - the_silver_searcher

- name: Install terminal and shell tools
  dnf:
    state: present
    name:
      - tmux
      - xterm
      - zsh
