---
- name: Install Discord
  dnf:
    state: present
    name: discord
  tags:
    - graphical

- name: Install Weechat
  dnf:
    state: present
    name: weechat

- name: Install Zoom
  flatpak:
    state: present
    name: us.zoom.Zoom
  tags:
    - graphical

# TODO: Install Slack
# sudo ed <<EOF
# f /etc/yum.repos.d/slack.repo
# i
# [slack]
# name=slack
# baseurl=https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
# enabled=1
# gpgcheck=0
# gpgkey=https://packagecloud.io/gpg.key
# sslverify=1
# sslcacert=/etc/pki/tls/certs/ca-bundle.crt
# .
# wq
# EOF
