---
- name: Install mitmproxy 5.1.1
  command:
    chdir: /tmp
    cmd: |
      curl https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz -o mitmproxy.tar.gz
      tar -xzf mitmproxy.tar.gz -C /usr/local/bin
      rm mitmproxy.tar.gz
    creates: /usr/local/bin/mitmproxy

- name: Install other network inspection tools
  dnf:
    state: present
    name:
      - nmap
      - wireshark

- name: Install alternate web browsers
  dnf:
    state: present
    name:
      - chromium
      - lynx
      - netsurf
      - w3m-img
