---
- name: Include tasks defined in this role
  ansible.builtin.include_tasks: "{{ tasks }}"
  loop:
    - install-build-tools.yml
    - install-debug-tools.yml
    - install-pkg-tools.yml
  loop_control:
    loop_var: tasks
