---
- name: Install essential interactive utilities
  dnf:
    state: present
    name:
      - tmux
      - nmap
      - htop

- name: Install debugging utilities
  dnf:
    state: present
    name:
      - strace
      - ltrace
