---
- name: Install essential interactive utilities
  dnf:
    state: present
    name:
      - tmux
      - nmap

- name: Install a terminal emulator (xterm)
  dnf:
    state: present
    name:
      - xterm
  tags:
    - graphical
