---
- name: Install essential interactive utilities
  ansible.builtin.dnf:
    state: present
    name:
      - tmux
      - nmap
      - htop

- name: Install troubleshooting tools
  ansible.builtin.dnf:
    state: present
    name:
      - strace
      - ltrace

# TODO: Investigate other options (e.g. urxvt, st)
- name: Install a terminal emulator (xterm)
  ansible.builtin.dnf:
    state: present
    name:
      - xterm
