- name: Check for existence of our desired font
  ansible.builtin.find:
    paths: '{{ fonts_dir }}'
    use_regex: true
    patterns:
      - '^{{ fonts.macbook_pro }}\.(?:.+\.)?gz$'
  register: font_files

- name: Use our desired font in the virtual console
  ansible.builtin.lineinfile:
    state: present
    path: /etc/vconsole.conf
    regexp: '^FONT='
    line: 'FONT="{{ fonts.macbook_pro }}"'
  when: font_files.matched == 1
