---
# FIXME: Ensure the correct version of Emacs is installed
- name: Install the latest Emacs from Fedora package repositories
  ansible.builtin.dnf:
    state: present
    name:
      - emacs

- name: Install dependencies for Doom Emacs
  ansible.builtin.dnf:
    state: present
    name:
      - git
      - findutils
      - fd-find
      - ripgrep

- name: Clone Doom Emacs
  vars: { ansible_become: false }
  git:
    repo: git@github.com:doomemacs/doomemacs.git
    dest: "{{ lookup('env', 'HOME') }}/.config/emacs"

- name: Install Doom Emacs
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/emacs/bin/doom install"

- name: Ensure proper installation of Doom Emacs
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/emacs/bin/doom doctor"

- name: Install dependencies for Doom Emacs modules
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/doom/install/run"
