---
- name: Import Microsoft GPG key to RPMDB
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Yum repo for Microsoft Visual Studio Code
  ansible.builtin.yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code - Microsoft RPM
  ansible.builtin.dnf:
    state: present
    name: code

- name: Install Visual Studio Code - OSS Flatpak
  vars: { ansible_become: false }
  community.general.flatpak:
    method: user
    state: present 
    name: app/com.visualstudio.code-oss/x86_64/stable
