---
# FIXME: Duplicate task (also in roles/host.interactive/tasks/install-editors.yml)
- name: Install Emacs with native compilation
  - dnf:
    state: present
    name:
      - emacs # Fedora 36 now packages Emacs 28.1 with native compilation

- name: Install dependencies for Doom Emacs
  dnf:
    state: present
    name:
      - git
      - findutils
      - fd-find
      - ripgrep

- name: Clone Doom Emacs
  vars: { ansible_become: false }
  git:
    repo: git@github.com:doomemacs/doomemacs.git
    dest: "{{ lookup('env', 'HOME') }}/.config/emacs"

- name: Install Doom Emacs
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/emacs/bin/doom install"

- name: Ensure proper installation of Doom Emacs
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/emacs/bin/doom doctor"

- name: Install dependencies for Doom Emacs modules
  vars: { ansible_become: false }
  command:
    cmd: "{{ lookup('env', 'HOME') }}/.config/doom/install/run"
