---
- name: Install Bitwarden desktop client
  vars: { ansible_become: false }
  community.general.flatpak:
    method: user
    state: present
    name: com.bitwarden
  tags:
    - graphical

# https://bitwarden.com/help/article/cli/
- name: Install Bitwarden CLI
  community.general.npm:
    name: '@bitwarden/cli'
    global: true
