---
# This is needed to install Google Chrome, which is non-free software.
#
# $ rpm -ql fedora-workstation-repositories
# /etc/yum.repos.d/_copr_phracek-PyCharm.repo
# /etc/yum.repos.d/google-chrome.repo
# /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
# /etc/yum.repos.d/rpmfusion-nonfree-steam.repo
#
- name: Install Fedora Workstation repositories
  dnf:
    state: present
    name: fedora-workstation-repositories
  tags:
    - graphical
    - nonfree

# I use Chrome as a workaround for when I have problems with codecs, DRM, etc.
# while using Firefox.  I leave Chromium uninstalled and primarily use Firefox.
- name: Install Google Chrome
  dnf:
    state: present
    name: google-chrome-stable
  tags:
    - graphical
    - nonfree
