---
- name: Include tasks defined in this role
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - install-discord.yml
    - install-signal.yml
    - install-slack.yml
    - install-weechat.yml
    - install-zoom.yml
