---
- name: Install Docker engine
  ansible.builtin.dnf:
    state: present
    name:
      - docker

- name: Start Docker daemon
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: docker

# TODO: Run as non-root user
