---
- name: Check for existence of /usr/local/bin/aws
  stat:
    path: /usr/local/bin/aws
  register: aws

# Use -e update=true to perform an update
- name: Install AWS CLI v2
  when: not aws.stat.exists or update
  block:
    # TODO: Support other architectures and platforms
    - name: Download AWS CLI v2 zipfile
      tags: awscli
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Extract AWS CLI v2 zipfile
      tags: awscli
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        creates: /tmp/aws/install

    # Using `changed_when: ...` is preferred over `creates: /usr/local/bin/aws`
    # because the former allows AWS CLI v2 updates while the latter does not.
    - name: Run AWS CLI v2 install script
      tags: awscli
      command: /tmp/aws/install -u
      register: result
      changed_when: "result.stdout == 'You can now run: /usr/local/bin/aws --version'"
      notify: Remove AWS CLI v2 temporary files
