---
- name: Clone documentation repo to ~/Documents/ref
  git:
    repo: git@github.com:eeowaa/ref.git
    dest: "{{ ansible_env.HOME }}/Documents/ref"

- name: Symlink ~/Documents/ref to ~/ref
  file:
    state: link
    src:  "{{ ansible_env.HOME }}/Documents/ref"
    dest: "{{ ansible_env.HOME }}/ref"
