---
- name: Initial setup through the first reboot
  hosts: workstations
  handlers:
    # <https://serverfault.com/questions/928200/global-handlers-in-ansible>
    - import_tasks: ../roles/ansible.meta/handlers/main.yml
  tasks:
    - name: Update RPMs
      dnf:
        name: "*"
        state: latest  # noqa 403
      notify: Reboot

    - name: Install and configure specifics to Macbook Pro
      import_role:
        name: machine.macbook
      when: computer == 'Macbook Pro'
      notify: Reboot
