---
- name: Test
  hosts: workstations
  tasks:
    - name: View filesystems
      command: df -h
      changed_when: false  # This task never changes the host.

      # `df` throws an error when run as root: <https://askubuntu.com/q/1227667>
      ignore_errors: true

    - name: View home data usage
      shell: |
        set -o pipefail
        du -s $HOME/* | sort -rn
      changed_when: false
