---
- name: Import Ubuntu keyserver GPG key to RPMDB
  ansible.builtin.rpm_key:
    state: present
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0

- name: Add Yum repo for GitHub CLI
  ansible.builtin.yum_repository:
    file: gh-cli
    name: gh-cli
    description: packages for the GitHub CLI
    baseurl: https://cli.github.com/packages/rpm
    enabled: true
    gpgcheck: true
    gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0

- name: Install gh
  ansible.builtin.dnf:
    state: present
    name: gh
