---
- name: Generate SSH key ~/.ssh/{{ ssh_key_filename }}
  vars: { ansible_become: false }
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    generate_ssh_key: true
    ssh_key_type: "{{ ssh_key_type }}"
    ssh_key_bits: "{{ ssh_key_bits }}"
    ssh_key_file: ".ssh/{{ ssh_key_filename }}"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    force: false
