---
# FIXME: Move this vars prompt to a playbook, where it belongs
vars_prompt:
  - name: "ssh_passphrase"
    prompt: "Enter the passphrase for the SSH key"

- name: Generate SSH key ~/.ssh/{{ ssh_key_filename }}
  vars: { ansible_become: false }
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: "{{ ssh_key_type }}"
    ssh_key_bits: "{{ ssh_key_bits }}"
    ssh_key_file: ".ssh/{{ ssh_key_filename }}"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    force: no
