---
- name: Install Wireshark
  ansible.builtin.dnf:
    state: present
    name:
      - wireshark
  tags:
    - graphical

- name: Install Wireshark CLI
  ansible.builtin.dnf:
    state: present
    name:
      - wireshark-cli
